### ISSUE TITLE
depends only fog-core

### ISSUE THREAD

**Issue by sawanoboly** [fog/fog-sakuracloud#6]
Just backlog.

**Comment by plribeiro3000** [comment]
@sawanoboly Could you do this asap? And open issues at fog or fog-core for you issues so we can all track it down?

**Comment by sawanoboly** [comment]
@plribeiro3000 

Maybe, does this issue is related to https://github.com/fog/fog/issues/3347?

I'll try to clear all problems for this issue. It'll takes about 1 or 2 weeks or so, Is that all right with you?

**Comment by plribeiro3000** [comment]
@sawanoboly Awesome. Thank you for the fast answer and work.

This is indeed related to fog/fog#3347. We need to make the providers work in a manner they won't break each other. Since fog depends on all `fog-providers`, having a provider depending on `fog` might/will cause problems.

Take your time to fix it and let me know if you need any help with it.

**Comment by plribeiro3000** [comment]
@sawanoboly I guess we can close this now, right?

**Comment by sawanoboly** [comment]
@plribeiro3000 

Yes, the fog-sakuracloud no longer depends on the fog! only depends on the fog-core.
We can remove fog-sakuracloud from fog dependencies.

And I've released as v1.0.0 https://rubygems.org/gems/fog-sakuracloud just now.

**Comment by plribeiro3000** [comment]
@sawanoboly :clap: 

Fog should depend on `fog-sakuracloud`. Just `fog-sakuracloud` tha should not depend on `fog`. =)
